### ISSUE TITLE
Redirection to Amazone issue

### ISSUE THREAD

**Issue by vojtasvoboda** [nella/victor#4]
![snimek obrazovky 2016-01-26 v 15 35 27](https://cloud.githubusercontent.com/assets/374917/12583393/e042c484-c442-11e5-91e0-7329411f0311.png)

I just downloaded file by `curl` and run `php victor.phar`

**Comment by Vrtak-CZ** [comment]
fixed by https://github.com/nella/victor/commit/7b8b467fc1709ae56867937cf889d7e9d0e135dc
