### ISSUE TITLE
Implement help command

### ISSUE THREAD

**Issue by enumag** [nella/victor#5]
`victor help` doesn't show anything useful. If I forget how to use victor I have to look to the GitHub page.

**Comment by Vrtak-CZ** [comment]
Help command is standard Symfony Console command. :-(

What about `victor help show`?

**Comment by enumag** [comment]
Ok. It actually does tell you something useful even if you don't know anything... Well sort of... The current help command tels you to use list command to see what commands are available and help <command> to see help to the command. Thus pointing me to `victor help show`.
